### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [copterust/vl53l0x#7]
This is what the README says:
```rs
let mut lsm = VL53L0X::default(l2c, &mut delay)?;
```
- But there is no `default` implementation for `VL53L0X`
- It's `VL53L0x` (with a lower case x), not `VL53L0X`

I could make an ESP32-C3 example ready to be built and runned by Cargo.

**Comment by little-arhat** [comment]
Thanks, was copy paste from [lsm](https://github.com/copterust/lsm303c).
